server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: mysql123




mybatis:
  type-aliases-package: com.dlwlrm4.dynamicds.entity
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
    root: debug
